package com.trekmate.exe.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents one active tour execution session.
 * groupId is kept short (8 chars) so it fits inside the 8-byte BLE packet field.
 */
@Entity
@Table(name = "exe_tour_sessions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ExeTourSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** UUID string assigned to this session's tour. Stored as-is, not in BLE packet. */
    @Column(nullable = false, unique = true, length = 36)
    private String tourId;

    /** 8-char uppercase alphanumeric ID. Fits in the 8-byte BLE groupId field. */
    @Column(nullable = false, unique = true, length = 8)
    private String groupId;

    /** 6-char uppercase alphanumeric join code shared with members. */
    @Column(nullable = false, unique = true, length = 6)
    private String joinCode;

    /** QR content: "trekmate://join?code=<joinCode>" */
    @Column(nullable = false, length = 100)
    private String qrPayload;

    /** 16-char compact userId of the tour leader (generated by Android UserIdGenerator). */
    @Column(nullable = false, length = 16)
    private String leaderId;

    /** false after the leader calls endTour. */
    @Column(nullable = false)
    @Builder.Default
    private boolean active = true;

    @Column(nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @OneToMany(mappedBy = "session", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @Builder.Default
    private List<ExeTourMember> members = new ArrayList<>();
}
